### ISSUE TITLE
Unable to click on some pieces on Brave Browser (Incompatibility with "Brave Shields")

### ISSUE THREAD

**Issue by draakje4685** [kishannareshpal/laserchess#5]
https://github.com/user-attachments/assets/c9df5432-edd6-46eb-a6b1-21073ff4c451

**Comment by kishannareshpal** [comment]
Hi @draakje4685, thanks for reporting this issue. Can I check the browser name and version where you experienced this?

Thanks!

**Comment by draakje4685** [comment]
i experienced this on brave in v1.0.0-alpha4.1

**Comment by kishannareshpal** [comment]
> i experienced this on brave in v1.0.0-alpha4.1

Thanks, I'll have a look to see if I can reproduce this in the same browser and push a fix.

**Comment by kishannareshpal** [comment]
Hi @draakje4685,

It turns out that the "Brave Shields" feature in this browser breaks interactions on this website. 
- To make the interactions work (clicking / dragging on all pieces), you'll have to disable the Shield on this website, as it is shown in the screen recording below. PS: This website is not supported by ads / trackers.

See before and after disabling "Brave Shields" in the screen recording below:

https://github.com/user-attachments/assets/b54f4100-8710-41bd-ae1e-bcd34d28f683

---

I've also, reported the website as being broken when enabling "Brave Shields" to the browser developers using the report feature present next to the toggle.

**Comment by kishannareshpal** [comment]
> can you also add the other starting setups and make the lazer turn.

I surely can. There's another issue open with the same request, but I have not had a chance to work on this project (#1)

I cannot promise when, but I'll see if I can try to resolve this sometime this week 👍

**Comment by draakje4685** [comment]
thanks
